services:
  # Spring Boot Backend Service
  - type: web
    name: valuecrop-backend
    runtime: docker
    dockerfilePath: ./Backend/valuecrop/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
